name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - stable
          - beta
          - nightly

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt install -y libevent-dev libssl-dev buffer-trigger
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.version }}
          override: true
      - name: clean
        run: cargo clean
      - name: fmt
        run: rustup component add rustfmt && cargo fmt -- --check
      - name: clippy
        run: rustup component add clippy && cargo clippy
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Generate code coverage
        run: cargo install cargo-tarpaulin && cargo tarpaulin --run-types Doctests Tests --verbose --all-features --workspace --timeout 120 --out Xml
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
